# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:57:17+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class GoogleCloudAssuredworkloadsV1beta1AcknowledgeViolationRequest(BaseModel):
    comment: Optional[str] = Field(
        None,
        description='Required. Business justification explaining the need for violation acknowledgement',
    )
    nonCompliantOrgPolicy: Optional[str] = Field(
        None,
        description='Optional. This field is deprecated and will be removed in future version of the API. Name of the OrgPolicy which was modified with non-compliant change and resulted in this violation. Format: projects/{project_number}/policies/{constraint_name} folders/{folder_id}/policies/{constraint_name} organizations/{organization_id}/policies/{constraint_name}',
    )


class GoogleCloudAssuredworkloadsV1beta1AcknowledgeViolationResponse(BaseModel):
    pass


class GoogleCloudAssuredworkloadsV1beta1AnalyzeWorkloadMoveResponse(BaseModel):
    blockers: Optional[List[str]] = Field(
        None,
        description='A list of blockers that should be addressed before moving the source project or project-based workload to the destination folder-based workload.',
    )


class RestrictionType(Enum):
    RESTRICTION_TYPE_UNSPECIFIED = 'RESTRICTION_TYPE_UNSPECIFIED'
    ALLOW_ALL_GCP_RESOURCES = 'ALLOW_ALL_GCP_RESOURCES'
    ALLOW_COMPLIANT_RESOURCES = 'ALLOW_COMPLIANT_RESOURCES'
    APPEND_COMPLIANT_RESOURCES = 'APPEND_COMPLIANT_RESOURCES'


class GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequest(BaseModel):
    restrictionType: Optional[RestrictionType] = Field(
        None,
        description='Required. The type of restriction for using gcp products in the Workload environment.',
    )


class GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesResponse(BaseModel):
    pass


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    RESOLVED = 'RESOLVED'
    UNRESOLVED = 'UNRESOLVED'
    EXCEPTION = 'EXCEPTION'


class GoogleCloudAssuredworkloadsV1beta1ViolationExceptionContext(BaseModel):
    acknowledgementTime: Optional[str] = Field(
        None, description='Timestamp when the violation was acknowledged.'
    )
    comment: Optional[str] = Field(
        None,
        description='Business justification provided towards the acknowledgement of the violation.',
    )
    principalEmail: Optional[str] = Field(
        None,
        description='Email address of the user (or service account) who acknowledged the violation.',
    )


class RemediationType(Enum):
    REMEDIATION_TYPE_UNSPECIFIED = 'REMEDIATION_TYPE_UNSPECIFIED'
    REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION = (
        'REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION'
    )
    REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION = (
        'REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION'
    )
    REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION = (
        'REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION'
    )
    REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION = (
        'REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION'
    )


class GoogleCloudAssuredworkloadsV1beta1ViolationRemediationInstructionsConsole(
    BaseModel
):
    additionalLinks: Optional[List[str]] = Field(
        None, description='Additional urls for more information about steps'
    )
    consoleUris: Optional[List[str]] = Field(
        None, description='Link to console page where violations can be resolved'
    )
    steps: Optional[List[str]] = Field(
        None, description='Steps to resolve violation via cloud console'
    )


class GoogleCloudAssuredworkloadsV1beta1ViolationRemediationInstructionsGcloud(
    BaseModel
):
    additionalLinks: Optional[List[str]] = Field(
        None, description='Additional urls for more information about steps'
    )
    gcloudCommands: Optional[List[str]] = Field(
        None, description='Gcloud command to resolve violation'
    )
    steps: Optional[List[str]] = Field(
        None, description='Steps to resolve violation via gcloud cli'
    )


class ComplianceRegime(Enum):
    COMPLIANCE_REGIME_UNSPECIFIED = 'COMPLIANCE_REGIME_UNSPECIFIED'
    IL4 = 'IL4'
    CJIS = 'CJIS'
    FEDRAMP_HIGH = 'FEDRAMP_HIGH'
    FEDRAMP_MODERATE = 'FEDRAMP_MODERATE'
    US_REGIONAL_ACCESS = 'US_REGIONAL_ACCESS'
    HIPAA = 'HIPAA'
    HITRUST = 'HITRUST'
    EU_REGIONS_AND_SUPPORT = 'EU_REGIONS_AND_SUPPORT'
    CA_REGIONS_AND_SUPPORT = 'CA_REGIONS_AND_SUPPORT'
    ITAR = 'ITAR'
    AU_REGIONS_AND_US_SUPPORT = 'AU_REGIONS_AND_US_SUPPORT'
    ASSURED_WORKLOADS_FOR_PARTNERS = 'ASSURED_WORKLOADS_FOR_PARTNERS'
    ISR_REGIONS = 'ISR_REGIONS'
    ISR_REGIONS_AND_SUPPORT = 'ISR_REGIONS_AND_SUPPORT'
    CA_PROTECTED_B = 'CA_PROTECTED_B'


class KajEnrollmentState(Enum):
    KAJ_ENROLLMENT_STATE_UNSPECIFIED = 'KAJ_ENROLLMENT_STATE_UNSPECIFIED'
    KAJ_ENROLLMENT_STATE_PENDING = 'KAJ_ENROLLMENT_STATE_PENDING'
    KAJ_ENROLLMENT_STATE_COMPLETE = 'KAJ_ENROLLMENT_STATE_COMPLETE'


class Partner(Enum):
    PARTNER_UNSPECIFIED = 'PARTNER_UNSPECIFIED'
    LOCAL_CONTROLS_BY_S3NS = 'LOCAL_CONTROLS_BY_S3NS'
    SOVEREIGN_CONTROLS_BY_T_SYSTEMS = 'SOVEREIGN_CONTROLS_BY_T_SYSTEMS'
    SOVEREIGN_CONTROLS_BY_SIA_MINSAIT = 'SOVEREIGN_CONTROLS_BY_SIA_MINSAIT'
    SOVEREIGN_CONTROLS_BY_PSN = 'SOVEREIGN_CONTROLS_BY_PSN'


class GoogleCloudAssuredworkloadsV1beta1WorkloadComplianceStatus(BaseModel):
    acknowledgedViolationCount: Optional[int] = Field(
        None,
        description='Count of active Violations which are acknowledged in the Workload.',
    )
    activeViolationCount: Optional[int] = Field(
        None, description="Count of active Violations which haven't been acknowledged."
    )


class EkmProvisioningErrorDomain(Enum):
    EKM_PROVISIONING_ERROR_DOMAIN_UNSPECIFIED = (
        'EKM_PROVISIONING_ERROR_DOMAIN_UNSPECIFIED'
    )
    UNSPECIFIED_ERROR = 'UNSPECIFIED_ERROR'
    GOOGLE_SERVER_ERROR = 'GOOGLE_SERVER_ERROR'
    EXTERNAL_USER_ERROR = 'EXTERNAL_USER_ERROR'
    EXTERNAL_PARTNER_ERROR = 'EXTERNAL_PARTNER_ERROR'
    TIMEOUT_ERROR = 'TIMEOUT_ERROR'


class EkmProvisioningErrorMapping(Enum):
    EKM_PROVISIONING_ERROR_MAPPING_UNSPECIFIED = (
        'EKM_PROVISIONING_ERROR_MAPPING_UNSPECIFIED'
    )
    INVALID_SERVICE_ACCOUNT = 'INVALID_SERVICE_ACCOUNT'
    MISSING_METRICS_SCOPE_ADMIN_PERMISSION = 'MISSING_METRICS_SCOPE_ADMIN_PERMISSION'
    MISSING_EKM_CONNECTION_ADMIN_PERMISSION = 'MISSING_EKM_CONNECTION_ADMIN_PERMISSION'


class EkmProvisioningState(Enum):
    EKM_PROVISIONING_STATE_UNSPECIFIED = 'EKM_PROVISIONING_STATE_UNSPECIFIED'
    EKM_PROVISIONING_STATE_PENDING = 'EKM_PROVISIONING_STATE_PENDING'
    EKM_PROVISIONING_STATE_FAILED = 'EKM_PROVISIONING_STATE_FAILED'
    EKM_PROVISIONING_STATE_COMPLETED = 'EKM_PROVISIONING_STATE_COMPLETED'


class GoogleCloudAssuredworkloadsV1beta1WorkloadEkmProvisioningResponse(BaseModel):
    ekmProvisioningErrorDomain: Optional[EkmProvisioningErrorDomain] = Field(
        None, description='Indicates Ekm provisioning error if any.'
    )
    ekmProvisioningErrorMapping: Optional[EkmProvisioningErrorMapping] = Field(
        None, description='Detailed error message if Ekm provisioning fails'
    )
    ekmProvisioningState: Optional[EkmProvisioningState] = Field(
        None, description='Indicates Ekm enrollment Provisioning of a given workload.'
    )


class GoogleCloudAssuredworkloadsV1beta1WorkloadKMSSettings(BaseModel):
    nextRotationTime: Optional[str] = Field(
        None,
        description='Required. Input only. Immutable. The time at which the Key Management Service will automatically create a new version of the crypto key and mark it as the primary.',
    )
    rotationPeriod: Optional[str] = Field(
        None,
        description='Required. Input only. Immutable. [next_rotation_time] will be advanced by this period when the Key Management Service automatically rotates a key. Must be at least 24 hours and at most 876,000 hours.',
    )


class ResourceType(Enum):
    RESOURCE_TYPE_UNSPECIFIED = 'RESOURCE_TYPE_UNSPECIFIED'
    CONSUMER_PROJECT = 'CONSUMER_PROJECT'
    CONSUMER_FOLDER = 'CONSUMER_FOLDER'
    ENCRYPTION_KEYS_PROJECT = 'ENCRYPTION_KEYS_PROJECT'
    KEYRING = 'KEYRING'


class GoogleCloudAssuredworkloadsV1beta1WorkloadResourceInfo(BaseModel):
    resourceId: Optional[str] = Field(
        None,
        description='Resource identifier. For a project this represents project_number.',
    )
    resourceType: Optional[ResourceType] = Field(
        None, description='Indicates the type of resource.'
    )


class GoogleCloudAssuredworkloadsV1beta1WorkloadResourceSettings(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='User-assigned resource display name. If not empty it will be used to create a resource with the specified name.',
    )
    resourceId: Optional[str] = Field(
        None,
        description="Resource identifier. For a project this represents project_id. If the project is already taken, the workload creation will fail. For KeyRing, this represents the keyring_id. For a folder, don't set this value as folder_id is assigned by Google.",
    )
    resourceType: Optional[ResourceType] = Field(
        None,
        description='Indicates the type of resource. This field should be specified to correspond the id to the right project type (CONSUMER_PROJECT or ENCRYPTION_KEYS_PROJECT)',
    )


class SetupError(Enum):
    SETUP_ERROR_UNSPECIFIED = 'SETUP_ERROR_UNSPECIFIED'
    ERROR_INVALID_BASE_SETUP = 'ERROR_INVALID_BASE_SETUP'
    ERROR_MISSING_EXTERNAL_SIGNING_KEY = 'ERROR_MISSING_EXTERNAL_SIGNING_KEY'
    ERROR_NOT_ALL_SERVICES_ENROLLED = 'ERROR_NOT_ALL_SERVICES_ENROLLED'
    ERROR_SETUP_CHECK_FAILED = 'ERROR_SETUP_CHECK_FAILED'


class SetupStatus(Enum):
    SETUP_STATE_UNSPECIFIED = 'SETUP_STATE_UNSPECIFIED'
    STATUS_PENDING = 'STATUS_PENDING'
    STATUS_COMPLETE = 'STATUS_COMPLETE'


class GoogleCloudAssuredworkloadsV1beta1WorkloadSaaEnrollmentResponse(BaseModel):
    setupErrors: Optional[List[SetupError]] = Field(
        None, description='Indicates SAA enrollment setup error if any.'
    )
    setupStatus: Optional[SetupStatus] = Field(
        None, description='Indicates SAA enrollment status of a given workload.'
    )


class GoogleProtobufEmpty(BaseModel):
    pass


class GoogleRpcStatus(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleCloudAssuredworkloadsV1beta1ViolationRemediationInstructions(BaseModel):
    consoleInstructions: Optional[
        GoogleCloudAssuredworkloadsV1beta1ViolationRemediationInstructionsConsole
    ] = Field(
        None,
        description='Remediation instructions to resolve violation via cloud console',
    )
    gcloudInstructions: Optional[
        GoogleCloudAssuredworkloadsV1beta1ViolationRemediationInstructionsGcloud
    ] = Field(
        None, description='Remediation instructions to resolve violation via gcloud cli'
    )


class GoogleCloudAssuredworkloadsV1beta1WorkloadCJISSettings(BaseModel):
    kmsSettings: Optional[GoogleCloudAssuredworkloadsV1beta1WorkloadKMSSettings] = (
        Field(
            None,
            description='Input only. Immutable. Settings used to create a CMEK crypto key.',
        )
    )


class GoogleCloudAssuredworkloadsV1beta1WorkloadFedrampHighSettings(BaseModel):
    kmsSettings: Optional[GoogleCloudAssuredworkloadsV1beta1WorkloadKMSSettings] = (
        Field(
            None,
            description='Input only. Immutable. Settings used to create a CMEK crypto key.',
        )
    )


class GoogleCloudAssuredworkloadsV1beta1WorkloadFedrampModerateSettings(BaseModel):
    kmsSettings: Optional[GoogleCloudAssuredworkloadsV1beta1WorkloadKMSSettings] = (
        Field(
            None,
            description='Input only. Immutable. Settings used to create a CMEK crypto key.',
        )
    )


class GoogleCloudAssuredworkloadsV1beta1WorkloadIL4Settings(BaseModel):
    kmsSettings: Optional[GoogleCloudAssuredworkloadsV1beta1WorkloadKMSSettings] = (
        Field(
            None,
            description='Input only. Immutable. Settings used to create a CMEK crypto key.',
        )
    )


class GoogleLongrunningOperation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[GoogleRpcStatus] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class GoogleCloudAssuredworkloadsV1beta1ViolationRemediation(BaseModel):
    compliantValues: Optional[List[str]] = Field(
        None,
        description='Values that can resolve the violation For example: for list org policy violations, this will either be the list of allowed or denied values',
    )
    instructions: Optional[
        GoogleCloudAssuredworkloadsV1beta1ViolationRemediationInstructions
    ] = Field(
        None, description='Required. Remediation instructions to resolve violations'
    )
    remediationType: Optional[RemediationType] = Field(
        None,
        description='Output only. Reemediation type based on the type of org policy values violated',
    )


class GoogleCloudAssuredworkloadsV1beta1Workload(BaseModel):
    billingAccount: Optional[str] = Field(
        None,
        description='Optional. The billing account used for the resources which are direct children of workload. This billing account is initially associated with the resources created as part of Workload creation. After the initial creation of these resources, the customer can change the assigned billing account. The resource name has the form `billingAccounts/{billing_account_id}`. For example, `billingAccounts/012345-567890-ABCDEF`.',
    )
    cjisSettings: Optional[GoogleCloudAssuredworkloadsV1beta1WorkloadCJISSettings] = (
        Field(
            None,
            description='Input only. Immutable. Settings specific to resources needed for CJIS.',
        )
    )
    complianceRegime: Optional[ComplianceRegime] = Field(
        None,
        description='Required. Immutable. Compliance Regime associated with this workload.',
    )
    complianceStatus: Optional[
        GoogleCloudAssuredworkloadsV1beta1WorkloadComplianceStatus
    ] = Field(
        None, description='Output only. Count of active Violations in the Workload.'
    )
    compliantButDisallowedServices: Optional[List[str]] = Field(
        None,
        description='Output only. Urls for services which are compliant for this Assured Workload, but which are currently disallowed by the ResourceUsageRestriction org policy. Invoke RestrictAllowedResources endpoint to allow your project developers to use these services in their environment."',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. Immutable. The Workload creation timestamp.'
    )
    displayName: Optional[str] = Field(
        None,
        description='Required. The user-assigned display name of the Workload. When present it must be between 4 to 30 characters. Allowed characters are: lowercase and uppercase letters, numbers, hyphen, and spaces. Example: My Workload',
    )
    ekmProvisioningResponse: Optional[
        GoogleCloudAssuredworkloadsV1beta1WorkloadEkmProvisioningResponse
    ] = Field(
        None,
        description='Optional. Represents the Ekm Provisioning State of the given workload.',
    )
    enableSovereignControls: Optional[bool] = Field(
        None,
        description='Optional. Indicates the sovereignty status of the given workload. Currently meant to be used by Europe/Canada customers.',
    )
    etag: Optional[str] = Field(
        None,
        description='Optional. ETag of the workload, it is calculated on the basis of the Workload contents. It will be used in Update & Delete operations.',
    )
    fedrampHighSettings: Optional[
        GoogleCloudAssuredworkloadsV1beta1WorkloadFedrampHighSettings
    ] = Field(
        None,
        description='Input only. Immutable. Settings specific to resources needed for FedRAMP High.',
    )
    fedrampModerateSettings: Optional[
        GoogleCloudAssuredworkloadsV1beta1WorkloadFedrampModerateSettings
    ] = Field(
        None,
        description='Input only. Immutable. Settings specific to resources needed for FedRAMP Moderate.',
    )
    il4Settings: Optional[GoogleCloudAssuredworkloadsV1beta1WorkloadIL4Settings] = (
        Field(
            None,
            description='Input only. Immutable. Settings specific to resources needed for IL4.',
        )
    )
    kajEnrollmentState: Optional[KajEnrollmentState] = Field(
        None,
        description='Output only. Represents the KAJ enrollment state of the given workload.',
    )
    kmsSettings: Optional[GoogleCloudAssuredworkloadsV1beta1WorkloadKMSSettings] = (
        Field(
            None,
            description='Input only. Settings used to create a CMEK crypto key. When set, a project with a KMS CMEK key is provisioned. This field is deprecated as of Feb 28, 2022. In order to create a Keyring, callers should specify, ENCRYPTION_KEYS_PROJECT or KEYRING in ResourceSettings.resource_type field.',
        )
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Optional. Labels applied to the workload.'
    )
    name: Optional[str] = Field(
        None,
        description='Optional. The resource name of the workload. Format: organizations/{organization}/locations/{location}/workloads/{workload} Read-only.',
    )
    partner: Optional[Partner] = Field(
        None, description='Optional. Partner regime associated with this workload.'
    )
    provisionedResourcesParent: Optional[str] = Field(
        None,
        description='Input only. The parent resource for the resources managed by this Assured Workload. May be either empty or a folder resource which is a child of the Workload parent. If not specified all resources are created under the parent organization. Format: folders/{folder_id}',
    )
    resourceSettings: Optional[
        List[GoogleCloudAssuredworkloadsV1beta1WorkloadResourceSettings]
    ] = Field(
        None,
        description='Input only. Resource properties that are used to customize workload resources. These properties (such as custom project id) will be used to create workload resources if possible. This field is optional.',
    )
    resources: Optional[
        List[GoogleCloudAssuredworkloadsV1beta1WorkloadResourceInfo]
    ] = Field(
        None,
        description='Output only. The resources associated with this workload. These resources will be created when creating the workload. If any of the projects already exist, the workload creation will fail. Always read only.',
    )
    saaEnrollmentResponse: Optional[
        GoogleCloudAssuredworkloadsV1beta1WorkloadSaaEnrollmentResponse
    ] = Field(
        None,
        description='Output only. Represents the SAA enrollment response of the given workload. SAA enrollment response is queried during GetWorkload call. In failure cases, user friendly error message is shown in SAA details page.',
    )
    violationNotificationsEnabled: Optional[bool] = Field(
        None,
        description='Optional. Indicates whether the e-mail notification for a violation is enabled for a workload. This value will be by default True, and if not present will be considered as true. This should only be updated via updateWorkload call. Any Changes to this field during the createWorkload call will not be honored. This will always be true while creating the workload.',
    )


class GoogleLongrunningListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[GoogleLongrunningOperation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )


class GoogleCloudAssuredworkloadsV1beta1ListWorkloadsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The next page token. Return empty if reached the last page.'
    )
    workloads: Optional[List[GoogleCloudAssuredworkloadsV1beta1Workload]] = Field(
        None, description='List of Workloads under a given parent.'
    )


class GoogleCloudAssuredworkloadsV1beta1Violation(BaseModel):
    acknowledged: Optional[bool] = Field(
        None, description='A boolean that indicates if the violation is acknowledged'
    )
    acknowledgementTime: Optional[str] = Field(
        None,
        description='Optional. Timestamp when this violation was acknowledged first. Check exception_contexts to find the last time the violation was acknowledged when there are more than one violations. This field will be absent when acknowledged field is marked as false.',
    )
    auditLogLink: Optional[str] = Field(
        None,
        description='Output only. Immutable. Audit Log Link for violated resource Format: https://console.cloud.google.com/logs/query;query={logName}{protoPayload.resourceName}{timeRange}{folder}',
    )
    beginTime: Optional[str] = Field(
        None,
        description='Output only. Time of the event which triggered the Violation.',
    )
    category: Optional[str] = Field(
        None,
        description='Output only. Category under which this violation is mapped. e.g. Location, Service Usage, Access, Encryption, etc.',
    )
    description: Optional[str] = Field(
        None,
        description='Output only. Description for the Violation. e.g. OrgPolicy gcp.resourceLocations has non compliant value.',
    )
    exceptionAuditLogLink: Optional[str] = Field(
        None,
        description='Output only. Immutable. Audit Log link to find business justification provided for violation exception. Format: https://console.cloud.google.com/logs/query;query={logName}{protoPayload.resourceName}{protoPayload.methodName}{timeRange}{organization}',
    )
    exceptionContexts: Optional[
        List[GoogleCloudAssuredworkloadsV1beta1ViolationExceptionContext]
    ] = Field(
        None,
        description='Output only. List of all the exception detail added for the violation.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Immutable. Name of the Violation. Format: organizations/{organization}/locations/{location}/workloads/{workload_id}/violations/{violations_id}',
    )
    nonCompliantOrgPolicy: Optional[str] = Field(
        None,
        description='Output only. Immutable. Name of the OrgPolicy which was modified with non-compliant change and resulted this violation. Format: projects/{project_number}/policies/{constraint_name} folders/{folder_id}/policies/{constraint_name} organizations/{organization_id}/policies/{constraint_name}',
    )
    orgPolicyConstraint: Optional[str] = Field(
        None,
        description='Output only. Immutable. The org-policy-constraint that was incorrectly changed, which resulted in this violation.',
    )
    remediation: Optional[GoogleCloudAssuredworkloadsV1beta1ViolationRemediation] = (
        Field(None, description='Output only. Compliance violation remediation')
    )
    resolveTime: Optional[str] = Field(
        None,
        description='Output only. Time of the event which fixed the Violation. If the violation is ACTIVE this will be empty.',
    )
    state: Optional[State] = Field(
        None, description='Output only. State of the violation'
    )
    updateTime: Optional[str] = Field(
        None,
        description='Output only. The last time when the Violation record was updated.',
    )


class GoogleCloudAssuredworkloadsV1beta1ListViolationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The next page token. Returns empty if reached the last page.'
    )
    violations: Optional[List[GoogleCloudAssuredworkloadsV1beta1Violation]] = Field(
        None, description='List of Violations under a Workload.'
    )
